### ISSUE TITLE
[todo-tutorial] SIFU version 0.3.0, invalid option -m

### ISSUE THREAD

**Issue by kernel-memory-dump** [drytools/sifu-documentation#3]
## Expected Behavior

run command sifu generate -m, which will generate project's code, settings and a script for creating database

## Current Behavior

D:\BBT\TWERK-IT\test>sifu generate -m
[ERROR] Unknown option 'm'. See 'sifu --help'.

D:\BBT\TWERK-IT\test>sifu generate --help
[SIFU]
  -d, --dir  <arg>         Directory to generate project to
  -f, --file  <arg>        Location path to .sifu specification file
  -n, --no-migrate         Ignores the creation of new migration file if a
                           difference with previous version is detected.
                           Migrations will be generated by default
  -r, --reset-migrations   Deletes all migration files, resets migration version

                           and creates a new, unified migration file
      --help               Show help message

## Steps to Reproduce (for bugs)

1. mkdir test; cd test;
2. sifu init test
3. sifu generate -m

## Your Environment

* Version used: 0.3.0
* Operating System and version (desktop or mobile): Windows 8.1 / x64

**Comment by profesor-test-dragan** [comment]
Thanks for reporting an issue, -m flag was removed in Sifu 0.3.0 but documentation is not still updated to reflect this changes. Now creating migration files is default behaviour when running 'sifu generate' without any flag, and user must specify flag '-n' if he does not want to create migration files.
New tutorials are in process of creation, and this changes will be published during next week.
